stages:
  - build
  - deploy_gcp

build_images:
  stage: build
  image: docker:20.10.21

  services:
    - docker:20.10.21-dind
  
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  
  script:
    - docker build -t flaventurini/app-cicd-dio:1.0 app/.
    - docker push flaventurini/app-cicd-dio:1.0

deploy_gcp:
  stage: deploy_gcp

  before_script:
    - chmod 400 $SSH_KEY
  
  script:
      - ssh -o StrictHostKeyChecking=no -i $SSH_KEY gcp@$SSH_SERVER "sudo rm -Rf ./app-cicd-dio/ && sudo git clone git@gitlab.com:flaventurini/app-cicd-dio.git && cd app-cicd-dio && sudo chmod +x ./script.sh && sudo ./script.sh"